### PR TITLE
much css, jquery for fast js

### PR DESCRIPTION
**Pull request by Compound-codes**
what i said

### CODE REVIEW

**Comment by Compound-codes** [comment]
thwere is also favicon (poato)

**Comment by python-nerd-3** [comment]
ew i hate the new background

**Comment by Compound-codes** [comment]
ok then :(

**Review by python-nerd-3 — CHANGES_REQUESTED** [review]
i changed the javascript so you need to adjust that also why yellow it looks bad i prefer the old color scheme

**Comment by Compound-codes** [comment]
maybe just don't use this pull request right now?

**Pull request closed without merging**
